### ISSUE TITLE
設定のインポート後のUI上からの画像追加時の order 処理の不具合

### ISSUE THREAD

**Issue by hinananoha** [nectarition/AirRegi-CustomCustomerDisplay#4]
- 概要
  - 「設定のインポート」から設定をインポートした後、UI上から画像を追加するとorder番号に不具合が発生し、新規に追加した画像の表示順を変えようとすると、その番号を境に画像の順番が変更できなくなる。なお、order番号とUI上の「表示順」は一致しない。

- 事象の再現方法
 1. 「設定のインポート」から広告UI部分に1枚以上の画像を含む設定をインポートする。
 2. 「広告エリア」の「保存」ボタンを押す
 3. （任意/画像が2枚以上のとき)設定画面を開き、「広告エリア」UIから画像を1枚削除し、「保存」を押して閉じる
 5. 再度設定画面を開き、「広告エリア」UIから画像を追加する
 6. 「広告エリア」の「保存」ボタンを押す（※任意）
 7. 不具合が発生する

- 不具合発生時の状態
  - 不具合が発生している状態で「設定のエクスポート」をすると、2つ以上の広告エリア項目の `order` の番号が重複する。
  - 重複の例は以下の通り：
    - 画像が1枚の時/または2枚以上の画像で画像を削除せず画像を追加した時は、最後の画像の `order` 番号が重複する
      - 例1 画像が1枚の時) `order: 1` の項目が2つ登場する
      - 例2 画像が4枚の時)  `order: 4` の項目が2つ登場する
    - 画像が2枚以上の時で最後の画像を削除した後に画像を追加したときは、削除した後の最後の画像の `order` 番号が重複する
      - 例 画像が5枚あり、5枚目の画像を削除した後に1枚画像を追加したとき) `order: 4` の項目が2つ登場する
    - 画像が2枚以上の時で、最後の画像以外を削除した時は、削除した画像の `order` が欠番となる。
      - 例：画像が2枚あり、1枚目の画像を削除すると、 `order: 1` が欠番となる。
    - 画像が2枚以上の時で、最後の画像以外を削除した後、画像を追加すると、欠番した次の番号が重複となる。
      - 例1 画像が2枚で1番目の画像を消したとき）`order: 1` が欠番となり、`order: 2` の項目が2つ登場する
      - 例2 画像が5枚で3番目の画像を消したとき）`order: 3` が欠番となり、`order: 4` に新規画像が追加され、そ項目が2つ登場する
  - 上記不具合が発生した状態で画像の順番を変更しようとすると、`order` の重複があるところを境に、その境より前/後に画像を移せなくなる
    - 例：5枚の画像で3番目の画像を消した後に1枚画像を追加した場合：UI上の 「1～3番」「4～5番」内では順番を変えることが出来るが、UI上の「3番」⇔「4番」に順番を変えることはできない。

ちょっと分かりづらいかもしれませんので、とりあえず事象の再現を行ってどういう状況か見てみてください。

**Comment by 10mocy** [comment]
@hinananoha 
修正し再現しないことを確認しましたので Close させていただきます。
ご報告ありがとうございました！
